name: Run Selenium Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- A WEBSHOP KONTÉNER ELINDÍTÁSA ---
      - name: Start Application (PrestaShop)
        run: |
          docker compose -f docker/docker-compose.yml up -d
          echo "Várakozás a PrestaShop betöltésére..."   
          sleep 240
          echo "Teszt adatok feltöltése"
          cat docker/full_cloneV2.sql | docker exec -i docker-db-1 mysql -u root -padmin prestashop

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Maven tests
        env:
          RUN_HEADLESS: "true"
        run: mvn -B clean test -DCI=true

      - name: Upload Allure and Surefire Reports
        uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: allure-and-maven-reports
          path: |
            target/allure-results/
            target/surefire-reports/
          retention-days: 30

      - name: Stop and remove containers
        if: always()
        run: docker compose -f docker/docker-compose.yml down